language: c

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

install:
  - sudo perl devkitARMupdate.pl

script:
  - make

env:
  global:
    secure: "QeQ3FDs8vOcB7+TJBPIszTPo6EuYOTcqTlC15fAXTHLLnGsY36ySSMKXKq9aV5mqJr9t92WGY169fAW35vg9wwQAx09A2EIEkaqLysozkNxaR9LralgwEEAXXJP2lD5NvJ0n13PMPloGyDCnjBRUjJ+WdDz5H6F329PbItKo5uE="

after_success:
  - sudo apt-get install lftp
  - TARBALL_NAME="`git show -s --format='%h - %s' | cut -c1-111`.tar.gz"
  - tar -cvzf "$TARBALL_NAME" Launcher.dat
  - lftp -c "open -u builds,$BUILD_PASSWORD sftp://archshift.com; put -O '/decrypt9/nightly/' '$TARBALL_NAME'"
